### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by wongm** [deanmoses/tacocat-gallery-zenphoto-rest-api#1]
Documentation is a little sparse, but I've managed to install this plugin on my demo site, and once I worked out the URL format, it worked straight away. Some sample links:

http://zenphoto.wongm.com/melbourne/?api=true
http://zenphoto.wongm.com/page/search/train?api=true

I had been considering writing a similar plugin, but no need given this exists!

**Comment by deanmoses** [comment]
Cool!  Glad it was useful.  I wasn't expecting other people to use it -- let me know if you have issues.

**Comment by acrylian** [comment]
I second that and will take a look later on. Until a user just asked about this plugin on our forum we - the Zenphoto team - didn't even know this existed at all! Welcome like any third party solution we don't have time to write ourselves. Although we have an externalFeed plugin that could be changed to also return JSON, too. 

Anyway, we have now added an entry for it on our extensions section:
http://www.zenphoto.org/news/tacocat-zenphoto-rest-api

**Comment by deanmoses** [comment]
I finally got back to this.   I made a separate repo for a more general REST API for Zenphoto that doesn't have my site's junk in it.   If you're going to link to anything, please use that one.

https://github.com/deanmoses/zenphoto-json-rest-api

**Comment by acrylian** [comment]
Great, thanks, we will change the link. We also have plans for an official (read only) and perhaps more complete rest API (including Zenpage pages, news etc. as well) for the next major release (in development but not in public and no release date set). 

We haven't startet with it yet as there are lots of other things to do first. But the plan is to follow your idea of using the normal front end urls (you would get an "based on" or "inspired by" credit in any case) and possibly have some kind of basic http authentification so sites may limit api access.

**Comment by deanmoses** [comment]
BTW, API access *is* limited, at least with browser-based clients.  The
HTTP headers the API returns restricts browser-based clients to subdomains
of where zenphoto is installed.  So you can install zenphoto on mysite.com
and serve your web app on app.mysite.com.  But random web apps on other
domains cannot connect.

It could be a configuration parameter to allow access from all domains, or
whitelist specific domains.

**Comment by acrylian** [comment]
Thanks, my bad. I wrote this before I looked at it respectively the new plugin. That's exactly how I think it should be as well. An option if anyone wants to open up a site on his own risk might be a good idea. But we best move discussion to your other repo. I
