### ISSUE TITLE
Plugin(s) should be in /plugins and not /zp-core/zp-extension

### ISSUE THREAD

**Issue by acrylian** [deanmoses/tacocat-gallery-zenphoto-rest-api#2]
This avoids the danger of being deleted/overwritten on Zenphoto updates.

**Comment by deanmoses** [comment]
Thanks.

**Comment by deanmoses** [comment]
This is fixed in the new repo that doesn't have my site-specific junk in it.  Please file any additional issues in that repo.

https://github.com/deanmoses/zenphoto-json-rest-api
