### ISSUE TITLE
Json without BOM

### ISSUE THREAD

**Issue by Yorium** [deanmoses/tacocat-gallery-zenphoto-rest-api#3]
I recently want to have a json output for my website so i use your extension.
But when i make a request (with js) the json output is UTF-8 with BOM. The problem is when i want to parse it i have a error : Unexpected token ?

How can I remove BOM ?

**Comment by deanmoses** [comment]
Huh.  I didn't intentionally insert a byte order mark anywhere in the JSON.   Any idea where in the output it is?  

If I cut and pasted code from somewhere else, it could be an invisible part of some string that I'm not seeing.

Will try to diagnose this weekend.

**Comment by deanmoses** [comment]
Sorry, I never saw anything related to this.  My guess is that you had an album with a weird title or description that was getting interpreted badly.

If you're interested, I created a new repo with a cleaner REST API that doesn't have my site-specific junk in it.

https://github.com/deanmoses/zenphoto-json-rest-api
