### ISSUE TITLE
Images not detected in album when there are any subalbum

### ISSUE THREAD

**Issue by jaanusnurmoja** [deanmoses/tacocat-gallery-zenphoto-rest-api#4]
if an album has one or more subalbums the images are missing from json output.

**Comment by crisc2000** [comment]
i have the same problem. if the album have an empty subalbum then the images are missing from the json

**Comment by deanmoses** [comment]
If you're still interested, this is fixed in a new repo that has a clean API without all my site-specific junk in it.

https://github.com/deanmoses/zenphoto-json-rest-api
