### ISSUE TITLE
A question maybe somebody can help

### ISSUE THREAD

**Issue by sw130637** [deanmoses/tacocat-gallery-zenphoto-rest-api#5]
I'm recently new to implementing API's.. I found this script hoping to be able to use it to allow zenphoto users to upload their images to my web server. I've scrolled through the code a few times and i'm not sure I understand how to call the script based on the user.. can anyone give me some advice in the right direction?

p.s. i'm coding in RoR (ruby on rails), it wasn't my choice, i'm working with an open source project.

**Comment by deanmoses** [comment]
This repo is obsolete.  There's a new repo with a cleaner REST API that doesn't have my site-specific junk in it.

https://github.com/deanmoses/zenphoto-json-rest-api
